# -*- coding: utf-8 -*-
"""Network _Intrusion _Detection _System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqoclPD1r5Lu75MUfq7Lj1S2_VAuDJnk
"""

pip install scapy

from scapy.all import sniff, IP, TCP
from datetime import datetime

# Define a function to log suspicious activities
def log_suspicious_activity(activity):
    with open("intrusion_log.txt", "a") as log_file:
        log_file.write(f"{datetime.now()} - {activity}\n")
    print(activity)

# Define a function to detect suspicious packets
def detect_suspicious_packet(packet):
    # Check if the packet has an IP layer
    if IP in packet:
        ip_layer = packet[IP]

        # Example Rule 1: Detect traffic to/from suspicious IP
        suspicious_ips = ["192.168.1.100", "10.0.0.1"]
        if ip_layer.src in suspicious_ips or ip_layer.dst in suspicious_ips:
            log_suspicious_activity(f"Suspicious IP detected: {ip_layer.src} -> {ip_layer.dst}")

        # Check if the packet has a TCP layer
        if TCP in packet:
            tcp_layer = packet[TCP]

            # Example Rule 2: Detect traffic on suspicious ports
            suspicious_ports = [23, 2323]  # Telnet ports (commonly used for attacks)
            if tcp_layer.sport in suspicious_ports or tcp_layer.dport in suspicious_ports:
                log_suspicious_activity(f"Suspicious port detected: {ip_layer.src}:{tcp_layer.sport} -> {ip_layer.dst}:{tcp_layer.dport}")

# Define a function to start the sniffer
def start_sniffer(interface):
    print(f"Starting sniffer on interface {interface}...")
    sniff(iface=interface, prn=detect_suspicious_packet, store=False)

# Main function
if __name__ == "__main__":
    interface = "eth0"  # Change this to the network interface you want to use
    start_sniffer(interface)